version: '3.9'

services:
  db:
    image: postgres:15
    container_name: db
    restart: always
    environment:
      POSTGRES_DB: write_down
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: server
    restart: always
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: write_down
      ACCESS_KEY: three_two_two
      REFRESH_KEY: two_three_three
    depends_on:
      - db
    ports:
      - '5000:5000'
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: client
    restart: always
    depends_on:
      - server
    environment:
      REACT_APP_API_URL: http://server:5000
    ports:
      - '3000:3000'
    volumes:
      - ./client:/usr/src/app
      - /usr/src/app/node_modules

volumes:
  postgres_data:
